In [7]:
## import the library 
import numpy

In [8]:
## import the library 
import numpy as np

In [14]:
lst = [1,2,3,4]
arr=np.array(lst)

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr.shape

(4,)

In [18]:
lst1=[1,2,3,4,5,]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1, lst2,lst3])

In [19]:
arr1.shape

(3, 5)

In [20]:
arr

array([1, 2, 3, 4])

In [21]:
#indexing
arr[3]

np.int64(4)

In [22]:
arr[3]=5

In [23]:
arr

array([1, 2, 3, 5])

In [24]:
arr[1:3]

array([2, 3])

In [25]:
arr[-1]

np.int64(5)

In [26]:
arr[:-1]

array([1, 2, 3])

In [27]:
arr[::]

array([1, 2, 3, 5])

In [28]:
arr[::-1]

array([5, 3, 2, 1])

In [29]:
arr[::-2]

array([5, 2])

In [30]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [31]:
arr1[:,1]

array([2, 3, 4])

In [32]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [33]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [34]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [35]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [36]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [39]:
arr1[:,3:].shape

(3, 2)

In [47]:
arr1[:,[0,4]]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [48]:
##EDA
arr


array([1, 2, 3, 5])

In [49]:
arr<2


array([ True, False, False, False])

In [50]:
arr[arr<2]

array([1])

In [52]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [53]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [60]:
##mechanism to create an array
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [63]:
np.arange(1, 20, 2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [65]:
arr *arr

array([ 1,  4,  9, 25])

In [72]:
arr1 *2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [73]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
np.random.randint(10, 50)

35

In [83]:
np.random.randint(10, 50, 4) #with 4 numbers

array([49, 23, 39, 14], dtype=int32)

In [84]:
np.random.randint(10, 50, 4).reshape(2, 2) #with reshape

array([[13, 13],
       [32, 45]], dtype=int32)

In [85]:
np.random.randn(5,6)

array([[ 1.83585749,  0.3442738 ,  0.42216549, -0.3845275 , -0.21076639,
        -1.13876624],
       [ 0.61991032,  0.60438496,  0.350344  ,  0.81143148,  0.94561942,
        -1.46492189],
       [-0.30561439,  0.0398617 ,  1.92286964,  0.54678492, -0.49928593,
         1.9002618 ],
       [-1.03734952, -2.19850815, -0.09476916, -1.49800246,  0.73184718,
        -1.04131787],
       [ 0.30977614, -0.11623646, -0.16429482,  0.11414299, -0.92534622,
         1.22914177]])

In [86]:
np.random.random_sample((4,7))

array([[0.68230989, 0.4184133 , 0.26177028, 0.66785361, 0.46020372,
        0.79670553, 0.39989652],
       [0.12062485, 0.54363003, 0.94639879, 0.28873749, 0.44635572,
        0.38973459, 0.30511106],
       [0.46210408, 0.12040556, 0.77871559, 0.4371777 , 0.23465252,
        0.31063221, 0.71279395],
       [0.57682757, 0.70865526, 0.54221942, 0.11356722, 0.88110467,
        0.78030525, 0.98901266]])